import { baseURL, routes, SearchParams, staticTxt, unionValues } from './constants';
import {
  getRandomHSL,
  getRandomMutedHSL,
  getRandomPastelHSL,
  getRandomVibrantHSL,
  isNotEmptyString,
  resolveApiErrorMessage,
} from './helpers';
import {
  useAdaptiveThumbnail,
  useKeyboardEvent,
  useResponsiveLazyLoad,
  useSyncURLParams,
} from './hooks';
import type {
  ICatDetails,
  IDogDetails,
  IFarmAnimalsDetails,
  IHorseDetails,
  IPet,
  IPetByCodeResponse,
  IPetByCodeWithSimilarPetsResponse,
  IPetMeta,
  IPetResponse,
  IPetWithDetailsResponse,
  Thumbnails,
  ThumbnailSizes,
} from './interfaces';
import {
  store,
  useGetPetByCodeQuery,
  useGetPetByCodeWithSpeciesDetailsAndSimilarPetsQuery,
  useGetPetByCodeWithSpeciesDetailsQuery,
  useGetPetsQuery,
  useGetPetsWithDetailsQuery,
} from './store';

export {
  baseURL,
  getRandomHSL,
  getRandomMutedHSL,
  getRandomPastelHSL,
  getRandomVibrantHSL,
  isNotEmptyString,
  resolveApiErrorMessage,
  routes,
  SearchParams,
  staticTxt,
  store,
  unionValues,
  useAdaptiveThumbnail,
  useGetPetByCodeQuery,
  useGetPetByCodeWithSpeciesDetailsAndSimilarPetsQuery,
  useGetPetByCodeWithSpeciesDetailsQuery,
  useGetPetsQuery,
  useGetPetsWithDetailsQuery,
  useKeyboardEvent,
  useResponsiveLazyLoad,
  useSyncURLParams,
};
export type {
  ICatDetails,
  IDogDetails,
  IFarmAnimalsDetails,
  IHorseDetails,
  IPet,
  IPetByCodeResponse,
  IPetByCodeWithSimilarPetsResponse,
  IPetMeta,
  IPetResponse,
  IPetWithDetailsResponse,
  Thumbnails,
  ThumbnailSizes,
};
